#!/bin/bash

source ~/.env


command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1
gh_ready_status=$?
if [ $gh_ready_status -ne 0 ]; then
  command -v gh >/dev/null
  if [ $? -ne 0 ]; then
    echo "⚠️  GitHub CLI is not installed. Exiting script."
  else
    echo "⚠️  GitHub CLI is not authenticated. Exiting script."
  fi
  exit 1
fi


alerts=$(gh api -X GET /repos/:owner/:repo/code-scanning/alerts \
  --paginate \
  --jq '.[] | select(.state == "open") | [.number, .rule.id, .rule.description, .most_recent_instance.message.text] | @tsv')

echo "$alerts" | column -t
