#!/bin/bash

source ~/.env


command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1
gh_ready_status=$?
if [ $gh_ready_status -ne 0 ]; then
  command -v gh >/dev/null
  if [ $? -ne 0 ]; then
    echo "⚠️  GitHub CLI is not installed. Exiting script."
  else
    echo "⚠️  GitHub CLI is not authenticated. Exiting script."
  fi
  exit 1
fi

# Check if a parameter is passed
alert_id="$1"
if [ -z "$alert_id" ]; then
  # No parameter passed, perform default paginated listing of alerts
  alerts=$(gh api -X GET /repos/:owner/:repo/code-scanning/alerts \
    --paginate \
    --jq '.[] | select(.state == "open") | [.number, .rule.id, .rule.description, .most_recent_instance.message.text] | @tsv')

  # Check if the API call was successful
  if [ $? -ne 0 ]; then
    echo "⚠️  Failed to retrieve alerts. Ensure Advanced Security is enabled for this repository."
    exit 1
  fi

  echo "$alerts" | while IFS=$'\t' read -r number rule_id rule_description message; do
    echo "-----------------------------"
    echo "Alert Number: $number"
    echo "Rule ID: $rule_id"
    echo "Description: $rule_description"
    echo "Message: $message"
  done

else
  # ID parameter passed
fi
