#!/bin/bash

source ~/.env


DIFF=$(git diff origin/main -U10)

# Check if there are any changes
if [ -z "$DIFF" ]; then
	echo "No changes found."
	exit 0
fi

# Display
# printf '%s\n' "$DIFF"

# Create commit message
printf '%s\n' "$DIFF" | \
jq -sR \
	--arg prompt "Make up a commit message from the following diffs.\n\n--------\n\n" \
	--arg model "gpt-4o" \
	--arg context_size "16383" \
	'{
		model: $model,
		messages: [
			{ role: "system", content: "You are an API. Only respond with the PLAIN TEXT response. As an API, do not repeat the request question given and do not explain or comment on anything." },
			{ role: "user", content: ($prompt + .) }
		]
	}' | \
JSON=$(curl -sSL -X POST "https://api.openai.com/v1/chat/completions" \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer $OPENAI_KEY" \
	--data @-)
if [ $? -ne 0 ]; then
	printf '%s\n' "$JSON"
	echo "\n"
	echo "Error calling OpenAI API."
	exit 1
else
	printf '%s\n' "$JSON" | jq -r '.choices[0].message.content'
fi
