#!/bin/bash

source ~/.env


DIFF=$(git diff origin/main -U10)

# Check if there are any changes
if [ -z "$DIFF" ]; then
	echo "No changes found."
	exit 0
fi

# Display
# printf '%s\n' "$DIFF"

# Create release notes
printf '%s\n' "$DIFF" | \
jq -sR \
	--arg prompt "This is the real diff. Do it for real now:\n\n" \
	--arg model "gpt-4o" \
	--arg context_size "16383" \
	'{
		model: $model,
		messages: [
			{ role: "system", content: "You are an API. Only respond with the PLAIN TEXT response. As an API, do not repeat the request question given, and do not explain or comment on anything more than necessary. You are given a Git diff. Meaning lines beginning with \"-\" are deletions and \"+\" are additions.\n\nFor a release page, explain in markdown bullet points what changes were made. Categorize them into Features, Fixes, Changes, and any other additional categories that you need. Use the format below, but skip sections that have none reported:\n\n**Features**\n - List new features that the user will see. Not backend tools and helpers.\n\n**Changes**\n - List changes that the user will encounter. Not backend refactors.\n\n**Fixes**\n - List fixed bugs that the user would have encountered. Not hidden backend things." },
			{ role: "user", content: "CALIBRATION: Give an example response where only 1 feature was added, and none reported for fixes nor changes." },
			{ role: "assistant", content: "**Features**\n - Add a checkbox to toggle hardware acceleration." },
			{ role: "user", content: "CALIBRATION: Give an example response where a change and bug fix were made, and none reported for features." },
			{ role: "assistant", content: "**Changes**\n - Lowered the cost of copper ingots to 10 ores per ingot.\n\n**Fixes**\n - Fix a bug where deconstructing something on a blueprint would crash the game." },
			{ role: "user", content: ($prompt + .) }
		]
	}' | \
curl -sSL -X POST "https://api.openai.com/v1/chat/completions" \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer $OPENAI_KEY" \
	--data @- | \
jq -r '.choices[0].message.content'
