#!/bin/bash

source ~/.env


DIFF=$(git diff origin/main -U10)

# Check if there are any changes
if [ -z "$DIFF" ]; then
	echo "No changes found."
	exit 0
fi

# Display
# printf '%s\n' "$DIFF"

# Create release notes
printf '%s\n' "$DIFF" | \
jq -sR \
	--arg prompt "For a release page, explain in markdown bullet points what changes were made. Categorize them into Features, Fixes, Changes, and any other categories that you need. Exclude the code block backticks.\n\n--------\n\n" \
	--arg model "gpt-4o-mini" \
	--arg context_size "16383" \
	'{
		model: $model,
		messages: [
			{ role: "system", content: "You are an API. Only respond with the PLAIN TEXT response. As an API, do not repeat the request question given, and do not explain or comment on anything more than necessary. Use the format below.\\n\\n---\\n\\n**Features**\\n  - List new features that the user will see. Not backend tools and helpers.\\n\\n**Changes**\\n  - List changes that the user will  encounter. Not refactors.\\n\\n**Fixes**\\n  - List fixed bugs that the user could have encountered. Not hidden backend things." },
			{ role: "user", content: ($prompt + .) }
		]
	}' | \
curl -sSL -X POST "https://api.openai.com/v1/chat/completions" \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer $OPENAI_KEY" \
	--data @- | \
jq -r '.choices[0].message.content'
