#!/bin/bash

source ~/.env


REPO_NAME=$(git remote get-url origin | sed -E 's/.*github.com[:/]([^/]+\/[^.]+)(\.git)?$/\1/')

while true; do
    echo ""
    echo "   Repo: $REPO_NAME"
    echo -n "❓ How many days of history to look up? Enter a number: "
    read days
    if [ -n "$days" ]; then
        break
    else
        echo "Expected a number."
    fi
done
echo ""




GIT_LOG=$(git log --author="nyaarium" --since="$days days ago" --pretty=format:"%s")

# Check if there are any commits
if [ -z "$GIT_LOG" ]; then
	echo "No commits found."
	exit 0
fi

# Display
# printf '%s\n' "$GIT_LOG"

# Summarize history
printf '%s\n' "$GIT_LOG" | \
jq -sR \
	--arg prompt "Summarize the following commit messages.\n\n--------\n\n" \
	--arg model "gpt-4o-mini" \
	--arg context_size "16383" \
	'{
		model: $model,
		messages: [
			{ role: "system", content: "You are an API. Only respond with the PLAIN TEXT response. As an API, do not repeat the request question given, and do not explain or comment on anything more than necessary." },
			{ role: "user", content: ($prompt + .) }
		]
	}' | \
curl -sSL -X POST "https://api.openai.com/v1/chat/completions" \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer $OPENAI_KEY" \
	--data @- | \
jq -r '.choices[0].message.content'
