services:
  dev:
    tty: true
    hostname: devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.devcontainer
      pull: true
      args:
        PROJECT_NAME: nyaascripts
    environment:
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock
    volumes:
      # SSH agent forwarding
      - ~/.ssh/agent.sock:/tmp/ssh-agent.sock
      # Workspace
      - ..:/workspace/nyaascripts:cached
      # Home
      - ../volumes/home:/home/vscode:cached
    networks:
      default:
      agent-team-bridge-network:
        aliases:
          - nyaascripts
networks:
  agent-team-bridge-network:
    name: agent-team-bridge
