FROM ghcr.io/nyaarium/agent-default:latest

ARG PROJECT_NAME
ENV PROJECT_NAME=$PROJECT_NAME
RUN test -n "$PROJECT_NAME" || (echo "Docker build error: PROJECT_NAME build arg is required" && exit 1) \
    && mkdir -p /workspace/$PROJECT_NAME \
	&& chown vscode:vscode /workspace /workspace/$PROJECT_NAME

# Install additional dependencies
# ...

COPY .devcontainer/post-*.sh /var/
ENV DEBIAN_FRONTEND=dialog
RUN /finalize
